fix hydra.errors.InstantiationException: Error in call to target 'nanoflash.components.collate.causal_lm_collate': TypeError("causal_lm_collate() missing 1 required positional argument: 'batch'")